version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: castores_ti_web
    #restart: always
    depends_on:
      - db-castoresti
    ports:
      - 8000:8000
    volumes: 
      - ./castores_ti_web/:/app

  db-castoresti:
    image: mysql
    container_name: castoresti
    #restart: always
    environment:
      MYSQL_DATABASE: castoresti-db
      MYSQL_USER: castoresti_user
      MYSQL_PASSWORD: "admin1234"
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db-castores_ti_web:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db:    
  db-castores_ti_web:    

